atlash: ./src/main.c ./src/eval.c ./src/errors.c ./src/parse.c ./src/errors.h ./src/parse.h ./src/eval.h
	gcc -o ./bin/atlash ./src/main.c ./src/eval.c ./src/errors.c ./src/parse.c

test: ./src/test.c
	gcc -o ./bin/test ./src/test.c